tasks:
  - init: make dev
    command: cargo test
vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - tamasfe.even-better-toml
    - matklad.rust-analyzer
ports:
  - port: 8080
    visibility: public
