[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
log = "0.4.17"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
lazy_static = "1.4.0"
async-trait = "0.1.53"
futures-util = "0.3.21"
rand = "0.8.5"
async-std = { version = "1.11.0", features = ["attributes", "tokio1"] }
nanoid = "0.4.0"
bitflags = "1.3.2"