[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async
async-std = { version = "1.11.0", features = ["attributes", "tokio1"] }
async-trait = "0.1.56"


# Database
rbatis = { version = "3.1", default-features = false, features = ["postgres", "runtime-async-std-native-tls", "upper_case_sql_keyword"] }
rbson = "2.0"


# HTTP
axum = "0.5.7"
reqwest = { version = "0.11", features = ["json"] }

# Serde
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.81"

# Logging
log = "0.4.17"
env_logger = "0.9.0"


# Security
tower-http = { version = "0.3.0", features = ["cors"] }
rust-argon2 = "1.0.0"
governor = "0.4.2"
validator = { version = "0.15", features = ["derive"] }


# Utility
dotenv = "0.15.0"
lazy_static = "1.4.0"
once_cell = "1.12.0"
nanoid = "0.4.0"
bitflags = "1.3.2"
dashmap = "5.3.4"
include_dir = "0.7.2"
regex = "1.5.6"
thiserror = "1.0.31"